<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxhUbA3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxhUbA3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxhUbA3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxhUbA3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCxhUbA3\App_KernelDevDebugContainer([
    'container.build_hash' => 'CxhUbA3',
    'container.build_id' => 'eee6b79d',
    'container.build_time' => 1636662689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxhUbA3');
